name: Auto Move to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress column
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/munirov/projects/2
          status-field: "Status"
          target-field-value: "In Progress"
          github-token: ${{ secrets.GTHB_PROJECTS_AUTO }}
